/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['h1[_ngcontent-%COMP%] {\n    font-size: 1.2em;\n    color: #999;\n    margin-bottom: 0;\n}\nh2[_ngcontent-%COMP%] {\n    font-size: 2em;\n    margin-top: 0;\n    padding-top: 0;\n}\nnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    padding: 5px 10px;\n    text-decoration: none;\n    margin-top: 10px;\n    display: inline-block;\n    background-color: #eee;\n    border-radius: 4px;\n}\nnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:link {\n    color: #607D8B;\n}\nnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\n    color: #039be5;\n    background-color: #CFD8DC;\n}\nnav[_ngcontent-%COMP%]   a.active[_ngcontent-%COMP%] {\n    color: #039be5;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtc3dhZ2dlci9jbGllbnQvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2Jhc3RpYW4vcHJveWVjdG9zL210aS9hcGxpY2FjaW9uZXMtd2ViL3F1ZW5hLXN3YWdnZXIvY2xpZW50L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map