/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.navbar-inverse[_ngcontent-%COMP%] {\n  background-color: #304668;\n  border-color: #252d37;\n}\n\n.navbar-brand[_ngcontent-%COMP%] {\n  padding: 2px 0;\n}\n\n.navbar-brand[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\n  height: 60px;\n  margin: 0;\n  padding: 0;\n}'];
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map