/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/forms';
import * as import6 from '@angular/http';
import * as import7 from '../../../src/app/app-routing.module';
import * as import8 from '../../../src/app/categorias/categoria.service';
import * as import9 from '../../../src/app/productos/producto.service';
import * as import10 from '../../../src/app/establecimientos/establecimiento.service';
import * as import11 from './categorias/admin-categoria-detail.component.ngfactory';
import * as import12 from './categorias/admin-categorias.component.ngfactory';
import * as import13 from './establecimientos/admin-establecimiento-detail.component.ngfactory';
import * as import14 from './establecimientos/admin-establecimientos.component.ngfactory';
import * as import15 from './productos/admin-producto-detail.component.ngfactory';
import * as import16 from './productos/admin-productos.component.ngfactory';
import * as import17 from './productos/producto-detail.component.ngfactory';
import * as import18 from './productos/productos.component.ngfactory';
import * as import19 from './establecimientos/establecimientos.component.ngfactory';
import * as import20 from './dashboard.component.ngfactory';
import * as import21 from './app.component.ngfactory';
import * as import22 from '../../../src/app/categorias/admin-categoria-detail.component';
import * as import23 from '../../../src/app/categorias/admin-categorias.component';
import * as import24 from '../../../src/app/establecimientos/admin-establecimiento-detail.component';
import * as import25 from '../../../src/app/establecimientos/admin-establecimientos.component';
import * as import26 from '../../../src/app/productos/admin-producto-detail.component';
import * as import27 from '../../../src/app/productos/admin-productos.component';
import * as import28 from '../../../src/app/productos/producto-detail.component';
import * as import29 from '../../../src/app/productos/productos.component';
import * as import30 from '../../../src/app/establecimientos/establecimientos.component';
import * as import31 from '../../../src/app/dashboard.component';
import * as import32 from '../../../src/app/app-config.constants';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _ɵba_10:import5.ɵba;
  _FormsModule_11:import5.FormsModule;
  _HttpModule_12:import6.HttpModule;
  _ɵa_13:any;
  _UrlSerializer_14:import3.DefaultUrlSerializer;
  _RouterOutletMap_15:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_16:any;
  _LocationStrategy_17:any;
  _Location_18:import2.Location;
  _Compiler_19:import0.Compiler;
  _NgModuleFactoryLoader_20:import0.SystemJsNgModuleLoader;
  _ROUTES_21:any[];
  _Router_22:any;
  _RouterModule_23:import3.RouterModule;
  _AppRoutingModule_24:import7.AppRoutingModule;
  _AppModule_25:import1.AppModule;
  __LOCALE_ID_26:any;
  __NgLocalization_27:import2.NgLocaleLocalization;
  __APP_ID_28:any;
  __IterableDiffers_29:any;
  __KeyValueDiffers_30:any;
  __DomSanitizer_31:import4.ɵe;
  __Sanitizer_32:any;
  __HAMMER_GESTURE_CONFIG_33:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_34:any[];
  __EventManager_35:import4.EventManager;
  __ɵDomSharedStylesHost_36:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_37:import4.ɵDomRendererFactory2;
  __RendererFactory2_38:any;
  __ɵSharedStylesHost_39:any;
  __Testability_40:import0.Testability;
  __Meta_41:import4.Meta;
  __Title_42:import4.Title;
  __ɵi_43:import5.ɵi;
  __BrowserXhr_44:import6.BrowserXhr;
  __ResponseOptions_45:import6.BaseResponseOptions;
  __XSRFStrategy_46:any;
  __XHRBackend_47:import6.XHRBackend;
  __RequestOptions_48:import6.BaseRequestOptions;
  __Http_49:any;
  __ActivatedRoute_50:any;
  __NoPreloading_51:import3.NoPreloading;
  __PreloadingStrategy_52:any;
  __RouterPreloader_53:import3.RouterPreloader;
  __PreloadAllModules_54:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_55:any;
  __APP_BOOTSTRAP_LISTENER_56:any[];
  _APP_CONFIG_57:any;
  __CategoriaService_58:import8.CategoriaService;
  __ProductoService_59:import9.ProductoService;
  __EstablecimientoService_60:import10.EstablecimientoService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import11.AdminCategoriaDetailComponentNgFactory,
      import12.AdminCategoriasComponentNgFactory,
      import13.AdminEstablecimientoDetailComponentNgFactory,
      import14.AdminEstablecimientosComponentNgFactory,
      import15.AdminProductoDetailComponentNgFactory,
      import16.AdminProductosComponentNgFactory,
      import17.ProductoDetailComponentNgFactory,
      import18.ProductosComponentNgFactory,
      import19.EstablecimientosComponentNgFactory,
      import20.DashboardComponentNgFactory,
      import21.AppComponentNgFactory
    ]
    ,[import21.AppComponentNgFactory]);
  }
  get _LOCALE_ID_26():any {
    if ((this.__LOCALE_ID_26 == null)) { (this.__LOCALE_ID_26 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_26;
  }
  get _NgLocalization_27():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_27 == null)) { (this.__NgLocalization_27 = new import2.NgLocaleLocalization(this._LOCALE_ID_26)); }
    return this.__NgLocalization_27;
  }
  get _APP_ID_28():any {
    if ((this.__APP_ID_28 == null)) { (this.__APP_ID_28 = import0.ɵg()); }
    return this.__APP_ID_28;
  }
  get _IterableDiffers_29():any {
    if ((this.__IterableDiffers_29 == null)) { (this.__IterableDiffers_29 = import0.ɵl()); }
    return this.__IterableDiffers_29;
  }
  get _KeyValueDiffers_30():any {
    if ((this.__KeyValueDiffers_30 == null)) { (this.__KeyValueDiffers_30 = import0.ɵm()); }
    return this.__KeyValueDiffers_30;
  }
  get _DomSanitizer_31():import4.ɵe {
    if ((this.__DomSanitizer_31 == null)) { (this.__DomSanitizer_31 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_31;
  }
  get _Sanitizer_32():any {
    if ((this.__Sanitizer_32 == null)) { (this.__Sanitizer_32 = this._DomSanitizer_31); }
    return this.__Sanitizer_32;
  }
  get _HAMMER_GESTURE_CONFIG_33():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_33 == null)) { (this.__HAMMER_GESTURE_CONFIG_33 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_33;
  }
  get _EVENT_MANAGER_PLUGINS_34():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_34 == null)) { (this.__EVENT_MANAGER_PLUGINS_34 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_33)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_34;
  }
  get _EventManager_35():import4.EventManager {
    if ((this.__EventManager_35 == null)) { (this.__EventManager_35 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_34,this.parent.get(import0.NgZone))); }
    return this.__EventManager_35;
  }
  get _ɵDomSharedStylesHost_36():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_36 == null)) { (this.__ɵDomSharedStylesHost_36 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_36;
  }
  get _ɵDomRendererFactory2_37():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_37 == null)) { (this.__ɵDomRendererFactory2_37 = new import4.ɵDomRendererFactory2(this._EventManager_35,this._ɵDomSharedStylesHost_36)); }
    return this.__ɵDomRendererFactory2_37;
  }
  get _RendererFactory2_38():any {
    if ((this.__RendererFactory2_38 == null)) { (this.__RendererFactory2_38 = this._ɵDomRendererFactory2_37); }
    return this.__RendererFactory2_38;
  }
  get _ɵSharedStylesHost_39():any {
    if ((this.__ɵSharedStylesHost_39 == null)) { (this.__ɵSharedStylesHost_39 = this._ɵDomSharedStylesHost_36); }
    return this.__ɵSharedStylesHost_39;
  }
  get _Testability_40():import0.Testability {
    if ((this.__Testability_40 == null)) { (this.__Testability_40 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_40;
  }
  get _Meta_41():import4.Meta {
    if ((this.__Meta_41 == null)) { (this.__Meta_41 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_41;
  }
  get _Title_42():import4.Title {
    if ((this.__Title_42 == null)) { (this.__Title_42 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_42;
  }
  get _ɵi_43():import5.ɵi {
    if ((this.__ɵi_43 == null)) { (this.__ɵi_43 = new import5.ɵi()); }
    return this.__ɵi_43;
  }
  get _BrowserXhr_44():import6.BrowserXhr {
    if ((this.__BrowserXhr_44 == null)) { (this.__BrowserXhr_44 = new import6.BrowserXhr()); }
    return this.__BrowserXhr_44;
  }
  get _ResponseOptions_45():import6.BaseResponseOptions {
    if ((this.__ResponseOptions_45 == null)) { (this.__ResponseOptions_45 = new import6.BaseResponseOptions()); }
    return this.__ResponseOptions_45;
  }
  get _XSRFStrategy_46():any {
    if ((this.__XSRFStrategy_46 == null)) { (this.__XSRFStrategy_46 = import6.ɵb()); }
    return this.__XSRFStrategy_46;
  }
  get _XHRBackend_47():import6.XHRBackend {
    if ((this.__XHRBackend_47 == null)) { (this.__XHRBackend_47 = new import6.XHRBackend(this._BrowserXhr_44,this._ResponseOptions_45,this._XSRFStrategy_46)); }
    return this.__XHRBackend_47;
  }
  get _RequestOptions_48():import6.BaseRequestOptions {
    if ((this.__RequestOptions_48 == null)) { (this.__RequestOptions_48 = new import6.BaseRequestOptions()); }
    return this.__RequestOptions_48;
  }
  get _Http_49():any {
    if ((this.__Http_49 == null)) { (this.__Http_49 = import6.ɵc(this._XHRBackend_47,this._RequestOptions_48)); }
    return this.__Http_49;
  }
  get _ActivatedRoute_50():any {
    if ((this.__ActivatedRoute_50 == null)) { (this.__ActivatedRoute_50 = import3.ɵf(this._Router_22)); }
    return this.__ActivatedRoute_50;
  }
  get _NoPreloading_51():import3.NoPreloading {
    if ((this.__NoPreloading_51 == null)) { (this.__NoPreloading_51 = new import3.NoPreloading()); }
    return this.__NoPreloading_51;
  }
  get _PreloadingStrategy_52():any {
    if ((this.__PreloadingStrategy_52 == null)) { (this.__PreloadingStrategy_52 = this._NoPreloading_51); }
    return this.__PreloadingStrategy_52;
  }
  get _RouterPreloader_53():import3.RouterPreloader {
    if ((this.__RouterPreloader_53 == null)) { (this.__RouterPreloader_53 = new import3.RouterPreloader(this._Router_22,this._NgModuleFactoryLoader_20,this._Compiler_19,this,this._PreloadingStrategy_52)); }
    return this.__RouterPreloader_53;
  }
  get _PreloadAllModules_54():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_54 == null)) { (this.__PreloadAllModules_54 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_54;
  }
  get _ROUTER_INITIALIZER_55():any {
    if ((this.__ROUTER_INITIALIZER_55 == null)) { (this.__ROUTER_INITIALIZER_55 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_55;
  }
  get _APP_BOOTSTRAP_LISTENER_56():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_56 == null)) { (this.__APP_BOOTSTRAP_LISTENER_56 = [this._ROUTER_INITIALIZER_55]); }
    return this.__APP_BOOTSTRAP_LISTENER_56;
  }
  get _CategoriaService_58():import8.CategoriaService {
    if ((this.__CategoriaService_58 == null)) { (this.__CategoriaService_58 = new import8.CategoriaService(this._Http_49,this._APP_CONFIG_57)); }
    return this.__CategoriaService_58;
  }
  get _ProductoService_59():import9.ProductoService {
    if ((this.__ProductoService_59 == null)) { (this.__ProductoService_59 = new import9.ProductoService(this._Http_49,this._APP_CONFIG_57)); }
    return this.__ProductoService_59;
  }
  get _EstablecimientoService_60():import10.EstablecimientoService {
    if ((this.__EstablecimientoService_60 == null)) { (this.__EstablecimientoService_60 = new import10.EstablecimientoService(this._Http_49,this._APP_CONFIG_57)); }
    return this.__EstablecimientoService_60;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵba_10 = new import5.ɵba();
    this._FormsModule_11 = new import5.FormsModule();
    this._HttpModule_12 = new import6.HttpModule();
    this._ɵa_13 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_14 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_15 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_16 = {};
    this._LocationStrategy_17 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_16);
    this._Location_18 = new import2.Location(this._LocationStrategy_17);
    this._Compiler_19 = new import0.Compiler();
    this._NgModuleFactoryLoader_20 = new import0.SystemJsNgModuleLoader(this._Compiler_19,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_21 = [[
        {
          path: 'admin/categorias/detail/:id',
          component: import22.AdminCategoriaDetailComponent
        }
        ,
        {
          path: 'admin/categorias',
          component: import23.AdminCategoriasComponent
        }
        ,
        {
          path: 'admin/establecimientos/detail/:id',
          component: import24.AdminEstablecimientoDetailComponent
        }
        ,
        {
          path: 'admin/establecimientos',
          component: import25.AdminEstablecimientosComponent
        }
        ,
        {
          path: 'admin/productos/detail/:id',
          component: import26.AdminProductoDetailComponent
        }
        ,
        {
          path: 'admin/productos',
          component: import27.AdminProductosComponent
        }
        ,
        {
          path: 'productos/detail/:id',
          component: import28.ProductoDetailComponent
        }
        ,
        {
          path: 'productos',
          component: import29.ProductosComponent
        }
        ,
        {
          path: 'establecimientos',
          component: import30.EstablecimientosComponent
        }
        ,
        {
          path: 'dashboard',
          component: import31.DashboardComponent
        }
        ,
        {
          path: '',
          redirectTo: '/dashboard',
          pathMatch: 'full'
        }

      ]
    ];
    this._Router_22 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_14,this._RouterOutletMap_15,this._Location_18,this,this._NgModuleFactoryLoader_20,this._Compiler_19,this._ROUTES_21,this._ROUTER_CONFIGURATION_16,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_23 = new import3.RouterModule(this._ɵa_13,this._Router_22);
    this._AppRoutingModule_24 = new import7.AppRoutingModule();
    this._AppModule_25 = new import1.AppModule();
    this._APP_CONFIG_57 = {
      API_ENDPOINT: 'http://api.quenamti.bastianc.info',
      GOOGLE_MAPS_EMBED_API_KEY: 'AIzaSyCavAyTJkyb70LwuYjB9P_CPwNluXG8guE'
    }
    ;
    return this._AppModule_25;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.ɵba)) { return this._ɵba_10; }
    if ((token === import5.FormsModule)) { return this._FormsModule_11; }
    if ((token === import6.HttpModule)) { return this._HttpModule_12; }
    if ((token === import3.ɵa)) { return this._ɵa_13; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_14; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_15; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_16; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_17; }
    if ((token === import2.Location)) { return this._Location_18; }
    if ((token === import0.Compiler)) { return this._Compiler_19; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_20; }
    if ((token === import3.ROUTES)) { return this._ROUTES_21; }
    if ((token === import3.Router)) { return this._Router_22; }
    if ((token === import3.RouterModule)) { return this._RouterModule_23; }
    if ((token === import7.AppRoutingModule)) { return this._AppRoutingModule_24; }
    if ((token === import1.AppModule)) { return this._AppModule_25; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_26; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_27; }
    if ((token === import0.APP_ID)) { return this._APP_ID_28; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_29; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_30; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_31; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_32; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_33; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_34; }
    if ((token === import4.EventManager)) { return this._EventManager_35; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_36; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_37; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_38; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_39; }
    if ((token === import0.Testability)) { return this._Testability_40; }
    if ((token === import4.Meta)) { return this._Meta_41; }
    if ((token === import4.Title)) { return this._Title_42; }
    if ((token === import5.ɵi)) { return this._ɵi_43; }
    if ((token === import6.BrowserXhr)) { return this._BrowserXhr_44; }
    if ((token === import6.ResponseOptions)) { return this._ResponseOptions_45; }
    if ((token === import6.XSRFStrategy)) { return this._XSRFStrategy_46; }
    if ((token === import6.XHRBackend)) { return this._XHRBackend_47; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_48; }
    if ((token === import6.Http)) { return this._Http_49; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_50; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_51; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_52; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_53; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_54; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_55; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_56; }
    if ((token === import32.APP_CONFIG)) { return this._APP_CONFIG_57; }
    if ((token === import8.CategoriaService)) { return this._CategoriaService_58; }
    if ((token === import9.ProductoService)) { return this._ProductoService_59; }
    if ((token === import10.EstablecimientoService)) { return this._EstablecimientoService_60; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_36 && this._ɵDomSharedStylesHost_36.ngOnDestroy());
    (this.__RouterPreloader_53 && this._RouterPreloader_53.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtbXRpL2NsaWVudC9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9iYXN0aWFuL3Byb3llY3Rvcy9tdGkvYXBsaWNhY2lvbmVzLXdlYi9xdWVuYS1tdGkvY2xpZW50L3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
