/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './producto-search.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../src/app/productos/producto-search.component';
import * as import3 from '@angular/common';
import * as import4 from '../../../../src/app/productos/producto.service';
import * as import5 from '@angular/http';
import * as import6 from '../../../../src/app/app-config.constants';
import * as import7 from '@angular/router';
const styles_ProductoSearchComponent:any[] = [import0.styles];
export const RenderType_ProductoSearchComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_ProductoSearchComponent,
  data: {}
}
);
function View_ProductoSearchComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.gotoDetail(v.context.$implicit)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '\n    ',
      '\n  '
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    const currVal_0:any = v.context.$implicit.nombre;
    ck(v,1,0,currVal_0);
  });
}
export function View_ProductoSearchComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,[[
        'searchBox',
        1
      ]
      ],(null as any),0,'input',[[
        'class',
        'form-control'
      ]
      ],(null as any),[[
        (null as any),
        'keyup'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import2.ProductoSearchComponent = v.component;
      if (('keyup' === en)) {
        const pd_0:any = ((<any>co.search(import1.ɵnov(v,0).value)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),5,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),2,(null as any),View_ProductoSearchComponent_1)),
    import1.ɵdid(401408,(null as any),0,import3.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import1.ɵpid(65536,import3.AsyncPipe,[import1.ChangeDetectorRef]),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import2.ProductoSearchComponent = v.component;
    const currVal_0:any = import1.ɵunv(v,5,0,import1.ɵnov(v,6).transform(co.productos));
    ck(v,5,0,currVal_0);
  },(null as any));
}
function View_ProductoSearchComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),2,'producto-search',([] as any[]),(null as any),(null as any),(null as any),View_ProductoSearchComponent_0,RenderType_ProductoSearchComponent)),
    import1.ɵprd(256,(null as any),import4.ProductoService,import4.ProductoService,[
      import5.Http,
      import6.APP_CONFIG
    ]
    ),
    import1.ɵdid(57344,(null as any),0,import2.ProductoSearchComponent,[
      import4.ProductoService,
      import7.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,2,0);
  },(null as any));
}
export const ProductoSearchComponentNgFactory:import1.ComponentFactory<import2.ProductoSearchComponent> = import1.ɵccf('producto-search',import2.ProductoSearchComponent,View_ProductoSearchComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtbXRpL2NsaWVudC9zcmMvYXBwL3Byb2R1Y3Rvcy9wcm9kdWN0by1zZWFyY2guY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtbXRpL2NsaWVudC9zcmMvYXBwL3Byb2R1Y3Rvcy9wcm9kdWN0by1zZWFyY2guY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9iYXN0aWFuL3Byb3llY3Rvcy9tdGkvYXBsaWNhY2lvbmVzLXdlYi9xdWVuYS1tdGkvY2xpZW50L3NyYy9hcHAvcHJvZHVjdG9zL3Byb2R1Y3RvLXNlYXJjaC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtbXRpL2NsaWVudC9zcmMvYXBwL3Byb2R1Y3Rvcy9wcm9kdWN0by1zZWFyY2guY29tcG9uZW50LnRzLlByb2R1Y3RvU2VhcmNoQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGlucHV0ICNzZWFyY2hCb3ggY2xhc3M9XCJmb3JtLWNvbnRyb2xcIiAoa2V5dXApPVwic2VhcmNoKHNlYXJjaEJveC52YWx1ZSlcIiAvPlxuPGRpdj5cbiAgPGRpdiAqbmdGb3I9XCJsZXQgcHJvZHVjdG8gb2YgcHJvZHVjdG9zIHwgYXN5bmNcIlxuICAgICAgIChjbGljayk9XCJnb3RvRGV0YWlsKHByb2R1Y3RvKVwiPlxuICAgIHt7cHJvZHVjdG8ubm9tYnJlfX1cbiAgPC9kaXY+XG48L2Rpdj5cbiIsIjxwcm9kdWN0by1zZWFyY2g+PC9wcm9kdWN0by1zZWFyY2g+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0VFO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQ0s7UUFBQTtRQUFBO01BQUE7TUFETDtJQUFBO0lBQ29DO01BQUE7TUFBQTtJQUFBO0lBQUE7OztJQUFBO0lBQUE7Ozs7O01BSHRDO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUF1QztRQUFBO1FBQUE7TUFBQTtNQUF2QztJQUFBO0lBQTJFO0lBQzNFO0lBQUs7SUFDSDtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBSztJQUdDO0lBQ0Y7Ozs7SUFKQztJQUFMLFNBQUssU0FBTDs7Ozs7SUNGRjtnQkFBQTs7O0lBQUE7SUFBQTtnQkFBQTs7O0lBQUE7S0FBQTs7O0lBQUE7OzsifQ==
