/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../src/app/categorias/categorias-widget.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/app/categorias/categoria.service';
const styles_CategoriasWidgetComponent:any[] = ([] as any[]);
export const RenderType_CategoriasWidgetComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CategoriasWidgetComponent,
  data: {}
}
);
function View_CategoriasWidgetComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'li',[[
        'class',
        'list-group-item'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'a',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.goToProductos(v.context.$implicit)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(ck,v) => {
    const currVal_0:any = v.context.$implicit.nombre;
    ck(v,3,0,currVal_0);
  });
}
export function View_CategoriasWidgetComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),12,'div',[[
        'class',
        'panel panel-default'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'panel-heading'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,'i',[[
        'class',
        'glyphicon glyphicon-tags'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['   Categorias\n  '])),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'ul',[[
        'class',
        'list-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_CategoriasWidgetComponent_1)),
    import0.ɵdid(401408,(null as any),0,import1.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import2.CategoriasWidgetComponent = v.component;
    const currVal_0:any = co.categorias;
    ck(v,10,0,currVal_0);
  },(null as any));
}
function View_CategoriasWidgetComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'categorias-widget',([] as any[]),(null as any),(null as any),(null as any),View_CategoriasWidgetComponent_0,RenderType_CategoriasWidgetComponent)),
    import0.ɵdid(57344,(null as any),0,import2.CategoriasWidgetComponent,[
      import3.Router,
      import4.CategoriaService
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const CategoriasWidgetComponentNgFactory:import0.ComponentFactory<import2.CategoriasWidgetComponent> = import0.ɵccf('categorias-widget',import2.CategoriasWidgetComponent,View_CategoriasWidgetComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtbXRpL2NsaWVudC9zcmMvYXBwL2NhdGVnb3JpYXMvY2F0ZWdvcmlhcy13aWRnZXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtbXRpL2NsaWVudC9zcmMvYXBwL2NhdGVnb3JpYXMvY2F0ZWdvcmlhcy13aWRnZXQuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9iYXN0aWFuL3Byb3llY3Rvcy9tdGkvYXBsaWNhY2lvbmVzLXdlYi9xdWVuYS1tdGkvY2xpZW50L3NyYy9hcHAvY2F0ZWdvcmlhcy9jYXRlZ29yaWFzLXdpZGdldC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtbXRpL2NsaWVudC9zcmMvYXBwL2NhdGVnb3JpYXMvY2F0ZWdvcmlhcy13aWRnZXQuY29tcG9uZW50LnRzLkNhdGVnb3JpYXNXaWRnZXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwicGFuZWwgcGFuZWwtZGVmYXVsdFwiPlxuICA8ZGl2IGNsYXNzPVwicGFuZWwtaGVhZGluZ1wiPlxuICAgIDxpIGNsYXNzPVwiZ2x5cGhpY29uIGdseXBoaWNvbi10YWdzXCI+PC9pPiAmbmJzcDsmbmJzcDtDYXRlZ29yaWFzXG4gIDwvZGl2PlxuICA8dWwgY2xhc3M9XCJsaXN0LWdyb3VwXCI+XG4gICAgPGxpIGNsYXNzPVwibGlzdC1ncm91cC1pdGVtXCIgKm5nRm9yPVwibGV0IGNhdCBvZiBjYXRlZ29yaWFzXCI+XG4gICAgICA8YSAoY2xpY2spPVwiZ29Ub1Byb2R1Y3RvcyhjYXQpXCI+e3tjYXQubm9tYnJlfX08L2E+XG4gICAgPC9saT5cbiAgPC91bD5cbjwvZGl2PlxuIiwiPGNhdGVnb3JpYXMtd2lkZ2V0PjwvY2F0ZWdvcmlhcy13aWRnZXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0tJO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMkQ7TUFDekQ7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFBRztRQUFBO1FBQUE7TUFBQTtNQUFIO0lBQUE7SUFBZ0M7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFrQjs7O0lBQWxCO0lBQUE7Ozs7O01BTnRDO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBaUM7TUFDL0I7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyQjtNQUN6QjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXdDO0lBQ3BDO01BQ047UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1QjtJQUNyQjtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUVLO0lBQ0Y7SUFDRDs7OztJQUowQjtJQUE1QixVQUE0QixTQUE1Qjs7Ozs7SUNMSjtnQkFBQTs7O0lBQUE7S0FBQTs7O0lBQUE7OzsifQ==
