/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtc3dhZ2dlci9jbGllbnQvc3JjL2FwcC9jYXRlZ29yaWFzL2NhdGVnb3JpYXMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2Jhc3RpYW4vcHJveWVjdG9zL210aS9hcGxpY2FjaW9uZXMtd2ViL3F1ZW5hLXN3YWdnZXIvY2xpZW50L3NyYy9hcHAvY2F0ZWdvcmlhcy9jYXRlZ29yaWFzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
//# sourceMappingURL=categorias.component.css.shim.ngstyle.js.map