/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.search-result[_ngcontent-%COMP%]{\n    border-bottom: 1px solid gray;\n    border-left: 1px solid gray;\n    border-right: 1px solid gray;\n    width:195px;\n    height: 16px;\n    padding: 5px;\n    background-color: white;\n    cursor: pointer;\n}\n.search-result[_ngcontent-%COMP%]:hover {\n    color: #eee;\n    background-color: #607D8B;\n}\n#search-box[_ngcontent-%COMP%]{\n    width: 200px;\n    height: 20px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmFzdGlhbi9wcm95ZWN0b3MvbXRpL2FwbGljYWNpb25lcy13ZWIvcXVlbmEtc3dhZ2dlci9jbGllbnQvc3JjL2FwcC9oZXJvZXMvaGVyby1zZWFyY2guY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2Jhc3RpYW4vcHJveWVjdG9zL210aS9hcGxpY2FjaW9uZXMtd2ViL3F1ZW5hLXN3YWdnZXIvY2xpZW50L3NyYy9hcHAvaGVyb2VzL2hlcm8tc2VhcmNoLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
